### ISSUE TITLE
EC-CUBE3.0.8で関連商品が登録されない

### ISSUE THREAD

**Issue by ghost** [EC-CUBE/related-product-plugin#16]
商品登録時に関連商品を選択し登録を行いますが、「商品を登録」ボタン押下後に関連商品のエリアを見ると値が何も入っていません。商品詳細ページにも関連商品は表示されていません。
何かコードを商品詳細ページに追加しなければいけないとかあるのでしょうか？

また他のプラグインが影響し、関連商品を検索しようとしてもできないケースが見られました。

**Comment by ghost** [comment]
Event,php内の registerRelatedProduct()にある、
if (!$response instanceof RedirectResponse) {}をコメントアウトすることで、表示されるようになりました。

とりあえず、そこでreturnされていたので、応急処置です。

**Comment by ghost** [comment]
https://github.com/EC-CUBE/related-product-plugin/blob/2d13efe4d8876b932f8b6194f7ae861cbe6b33a8/Event.php

のソースに置き換えたらエラーが解消されました。

**Comment by ryo-endo** [comment]
コメントできておらず申し訳ありません。
最新のコードに置き換えたら解消したとのことですので、CLOSEさせていただきます。
ご報告ありがとうございました。
