### ISSUE TITLE
商品点数が増加するとメモリオーバーとなる

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/related-product-plugin#19]
## 現象

http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=17657&forum=11&post_id=76613#forumpost76613
## 原因

（おそらく） entity typeとしてProductエンティティを指定している箇所で全件取得を行っている可能性がある。
https://github.com/EC-CUBE/related-product-plugin/blob/master/Form/Type/Admin/RelatedProductType.php#L26

**Comment by izayoi256** [comment]
entityタイプが重いのに加え、display:none;な商品のselectが出力されていたのも原因のようです。5万件だと5倍の25万個のoption要素が…。

**Comment by chihiro-adachi** [comment]
ご対応ありがとうございます。確認しました。
#25
