### ISSUE TITLE
商品登録画面に項目追加するプラグインとの共存ができていない

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/related-product-plugin#27]
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=17557&forum=13&post_id=76304

**Comment by ryo-endo** [comment]
登録ありがとうございます。

**Comment by ryo-endo** [comment]
1.0.0対応(#39)で、競合起きないことを確認しました。
`$form['related_collection']->isValid()`というように、自分の部分だけValidationするように変更しています。
投稿の共有ありがとうございました。

**Comment by nobuhiko** [comment]
👍
