### ISSUE TITLE
フリーエリアにhtmlタグを含む文字列を登録すると、関連商品の登録エリアが表示されない

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/related-product-plugin#28]
## 現象

以下の通り
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=17800&forum=13&post_id=77164#forumpost77164
## 原因

入力された内容がエスケープされており、str_replaceでの置換時に一致しないため。

**Comment by ryo-endo** [comment]
1.0.0(#39)で対応済みです。
