### ISSUE TITLE
関連商品の選択肢が検索結果に関係なく表示される

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/related-product-plugin#4]
## 事象

関連商品の「商品を選択」の下のセレクトボックスで、「商品を選択」で検索したものとは関係ない商品がでてきている。また、現在編集中の商品（自分自身）も選択できてしまう。  
### 期待

関連商品を選択するセレクトボックスは、検索結果のカテゴリの商品のみ
もしくは2.13のように、検索で選択した商品の商品名が表示される

**Comment by shinichi-takahashi** [comment]
#6 にて期待する動作へと修正済

**Comment by ryo-endo** [comment]
> 現在編集中の商品（自分自身）も選択できてしまう

の部分が期待動作になっていないので再OPEN。
