### ISSUE TITLE
フォームの幅が不揃い

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/related-product-plugin#5]
関連商品のセレクトボックスと説明のテキストエリアのサイズが非常にせまく
商品名が表示されない、テキスト入力が不適切な状態

商品説明など他の項目と幅を揃えたい

**Comment by shinichi-takahashi** [comment]
#6 にてセレクトボックス自体がなくなりました。

**Comment by ryo-endo** [comment]
項目なくなっているのでCLOSEします。
